### ISSUE TITLE
Verwaiste Seite dokumentation/gone.html

### ISSUE THREAD

**Issue by ulm** [gentoo-ev/www.gentoo.de#23]
Die Seite https://gentoo.de/dokumentation/gone.html scheint verwaist zu sein. Früher gab es eine Weiterleitung von `/doc/de`, die man [hier](https://web.archive.org/web/20161018101522/http://www.gentoo.de/doc/de/index.xml) noch sehen kann.

Ist da etwas kaputtgegangen, oder kann gone.html weg? (Die Wiki-Suche ist ganz nett, und man könnte sie in `dokumentation/index.html` integrieren.)

@hartwork

**Comment by hartwork** [comment]
@ulm vielleicht hilft ie History auf https://github.com/gentoo-ev/www.gentoo.de/commits/87726b3829b0fdf50d2c393554d0ddcbc05dd4a2/dokumentation/gone.html beim Klären — ich war da nicht beteiligt. Bitte mach, wie du denkst.
