### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by rugk** [gentoo-ev/www.gentoo.de#7]
Wie wäre es denn HTTPS anzubieten? Zum Beispiel mit [Let's Encrypt](https://letsencrypt.org/).

**Comment by hartwork** [comment]
Ist jetzt auf Let's Encrypt umgestellt, nutzt [`app-crypt/wile` aus dem betagarden-Overlay](https://cgit.gentoo.org/proj/betagarden.git/tree/app-crypt/wile) und läuft per Cronjob.

Sorry, dass das so lange gedauert hat.

**Comment by rugk** [comment]
Später ist besser als nie. :smiley:
