### ISSUE TITLE
empty spreadshirt product list

### ISSUE THREAD

**Issue by dastergon** [gentoo-ev/www.gentoo.de#8]
When I click to the Gentoo Shop icon in the [front page](http://www.gentoo.de) I get a message from `spreadshirt` platform that there are no products.

**Comment by hartwork** [comment]
Hi Pavlos,
it seems the link broke on the side of SpreadShirt. I have updated the link to https://22258.spreadshirt.de/ now on the [front page](https://gentoo-ev.org/wiki/Main_Page).
Best, Sebastian
